In [20]:
# STANDARD LIBRARIES
import pandas as pd
import numpy as np
import glob

# Create Master DataFrame

### `data`

In [5]:
# READING THIS FILE IN AS RESULTS IN A DtypeWarning
# AND ADVISES THE USER TO SET 'low_memory=False'

data = pd.read_csv("../data/fy19fullpropassess.csv", low_memory=False)

## Investigate `data`

In [6]:
data.head()

,PID,CM_ID,GIS_ID,ST_NUM,ST_NAME,ST_NAME_SUF,UNIT_NUM,ZIPCODE,PTYPE,LU,...,U_BTH_STYLE2,U_BTH_STYLE3,U_KITCH_TYPE,U_KITCH_STYLE,U_HEAT_TYP,U_AC,U_FPLACE,U_INT_FIN,U_INT_CND,U_VIEW
0,502550008,502550000.0,502550000,87,BEACON,ST,2-F,2108.0,102,CD,...,M,NaN,O,M,W,N,1.0,N,G,A
1,502550010,502550000.0,502550000,87,BEACON,ST,2-R,2108.0,102,CD,...,NaN,NaN,O,S,W,N,1.0,N,A,A
2,502550012,502550000.0,502550000,87,BEACON,ST,3-F,2108.0,102,CD,...,S,NaN,O,M,W,N,1.0,N,A,G
3,502550014,502550000.0,502550000,87,BEACON,ST,3-R,2108.0,102,CD,...,NaN,NaN,O,N,W,N,1.0,S,A,G
4,502550016,502550000.0,502550000,87,BEACON,ST,4,2108.0,102,CD,...,M,M,O,L,W,C,2.0,N,E,G

In [7]:
data.shape

(174668, 75)

In [8]:
data.dtypes

PID            int64
CM_ID        float64
GIS_ID         int64
ST_NUM        object
ST_NAME       object
              ...
U_AC          object
U_FPLACE     float64
U_INT_FIN     object
U_INT_CND     object
U_VIEW        object
Length: 75, dtype: object

In [9]:
# DATAFRAMES BY DATATYPE

# data.select_dtypes(include="object")["lu"].value_counts()
# data.select_dtypes(include="int64")
# data.select_dtypes(include="float64")
# data.select_dtypes(include="bool")

In [10]:
data.isna().sum()

PID               0
CM_ID         92630
GIS_ID            0
ST_NUM            0
ST_NAME           0
              ...
U_AC         110624
U_FPLACE     110624
U_INT_FIN    110624
U_INT_CND    110624
U_VIEW       110624
Length: 75, dtype: int64

In [11]:
data.columns

Index(['PID', 'CM_ID', 'GIS_ID', 'ST_NUM', 'ST_NAME', 'ST_NAME_SUF',
       'UNIT_NUM', 'ZIPCODE', 'PTYPE', 'LU', 'OWN_OCC', 'OWNER',
       'MAIL_ADDRESSEE', 'MAIL_ADDRESS', 'MAIL CS', 'MAIL_ZIPCODE', 'AV_LAND',
       'AV_BLDG', 'AV_TOTAL', 'GROSS_TAX', 'LAND_SF', 'YR_BUILT', 'YR_REMOD',
       'GROSS_AREA', 'LIVING_AREA', 'NUM_FLOORS', 'STRUCTURE_CLASS',
       'R_BLDG_STYL', 'R_ROOF_TYP', 'R_EXT_FIN', 'R_TOTAL_RMS', 'R_BDRMS',
       'R_FULL_BTH', 'R_HALF_BTH', 'R_BTH_STYLE', 'R_BTH_STYLE2',
       'R_BTH_STYLE3', 'R_KITCH', 'R_KITCH_STYLE', 'R_KITCH_STYLE2',
       'R_KITCH_STYLE3', 'R_HEAT_TYP', 'R_AC', 'R_FPLACE', 'R_EXT_CND',
       'R_OVRALL_CND', 'R_INT_CND', 'R_INT_FIN', 'R_VIEW', 'S_NUM_BLDG',
       'S_BLDG_STYL', 'S_UNIT_RES', 'S_UNIT_COM', 'S_UNIT_RC', 'S_EXT_FIN',
       'S_EXT_CND', 'U_BASE_FLOOR', 'U_NUM_PARK', 'U_CORNER', 'U_ORIENT',
       'U_TOT_RMS', 'U_BDRMS', 'U_FULL_BTH', 'U_HALF_BTH', 'U_BTH_STYLE',
       'U_BTH_STYLE2', 'U_BTH_STYLE3', 'U_KITCH_TYPE', 'U_KITCH_STYLE',
       'U_HEAT_TYP', 'U_AC', 'U_FPLACE', 'U_INT_FIN', 'U_INT_CND', 'U_VIEW'],
      dtype='object')

In [12]:
data["MAIL_ADDRESS"]

0              87 BEACON ST #2F
1              87 BEACON ST #2R
2             87 BEACON ST #3-F
3               348 CONGRESS PL
4                  87 BEACON ST
                  ...
174663                4 LAKE ST
174664           513 E BROADWAY
174665    2203 COMMONWEALTH AVE
174666    2203 COMMONWEALTH AVE
174667    2203 COMMONWEALTH AVE
Name: MAIL_ADDRESS, Length: 174668, dtype: object

In [13]:
data["ST_NAME"].isna().sum() # 0
data["ST_NUM"].isna().sum() # 0
data["ST_NAME_SUF"].isna().sum() # 539
data["ZIPCODE"].isna().sum() # 7

7

# Public Works Violations DataFrame

## `pw_df`

In [14]:
pw_df = pd.read_csv("../data/public-works-violations/tmpcmn0p2r0.csv", low_memory=False)

In [15]:
print(pw_df.shape)
pw_df.head()

(481429, 17)

,ticket_no,status_dttm,status,code,value,description,stno,sthigh,street,suffix,city,state,zip,sam_id,latitude,longitude,location
0,CE494577,2020-05-26 07:29:00,Open,1,25,Improper storage trash: res,118,NaN,Commonwealth,AVE,Boston,MA,02116,37097,42.351830,-71.076720,"(42.3518299997315, -71.0767200009251)"
1,CE494575,2020-05-26 07:26:00,Open,1,25,Improper storage trash: res,1037,,River,ST,Hyde Park,MA,02136,344142,42.259883,-71.117176,"(42.2598833641543, -71.1171758487242)"
2,CE494575,2020-05-26 07:26:00,Open,3,100,Overfilling of barrel/dumpster,1037,,River,ST,Hyde Park,MA,02136,344142,42.259883,-71.117176,"(42.2598833641543, -71.1171758487242)"
3,CE494576,2020-05-26 07:25:00,Open,3,100,Overfilling of barrel/dumpster,110,NaN,Warren,ST,Allston,MA,02135,143122,42.349353,-71.141434,"(42.3493529997196, -71.1414340008673)"
4,CE494576,2020-05-26 07:25:00,Open,1,25,Improper storage trash: res,110,NaN,Warren,ST,Allston,MA,02135,143122,42.349353,-71.141434,"(42.3493529997196, -71.1414340008673)"

In [16]:
pw_df.dtypes

ticket_no       object
status_dttm     object
status          object
code            object
value            int64
description     object
stno            object
sthigh          object
street          object
suffix          object
city            object
state           object
zip             object
sam_id           int64
latitude       float64
longitude      float64
location        object
dtype: object

In [17]:
pw_df.isna().sum()

ticket_no           0
status_dttm         0
status              0
code                0
value               0
description         0
stno                0
sthigh         360099
street              0
suffix           2680
city                1
state               0
zip               132
sam_id              0
latitude            0
longitude           0
location            0
dtype: int64

# Crime Incident Reports

## `crime_df`

In [27]:
crime_df = pd.read_csv("../data/crime-incident-reporting/tmpuxm3s5u0.csv", low_memory=False)

In [30]:
crime_df.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,TESTTEST2,423,NaN,ASSAULT - AGGRAVATED,External,,0,2019-10-16 00:00:00,2019,10,Wednesday,0,NaN,RIVERVIEW DR,NaN,NaN,"(0.00000000, 0.00000000)"
1,I92102201,3301,NaN,VERBAL DISPUTE,E13,583,0,2019-12-20 03:08:00,2019,12,Friday,3,NaN,DAY ST,42.325122,-71.107779,"(42.32512200, -71.10777900)"
2,I92097173,3115,NaN,INVESTIGATE PERSON,C11,355,0,2019-10-23 00:00:00,2019,10,Wednesday,0,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755500, -71.05970900)"
3,I92094519,3126,NaN,WARRANT ARREST - OUTSIDE OF BOSTON WARRANT,D14,765,0,2019-11-22 07:50:00,2019,11,Friday,7,NaN,BROOKS ST,42.355120,-71.162678,"(42.35512000, -71.16267800)"
4,I92089785,3005,NaN,SICK ASSIST,E13,574,0,2019-11-05 18:00:00,2019,11,Tuesday,18,NaN,WASHINGTON ST,42.309718,-71.104294,"(42.30971800, -71.10429400)"

In [ ]:
crime["INCIDENT_NUMBER"].isna().sum()

In [ ]:
crime["Location"].isna().sum()

In [ ]:
crime.loc[crime["INCIDENT_NUMBER"] == "TEST"]

In [ ]:
crime["INCIDENT_NUMBER"].value_counts()

# 311 Requests

## `requests`

In [21]:
requests_df = pd.read_csv("../data/311-requests/311_service_requests_2019.csv")

In [22]:
print(requests_df.shape)
requests_df.head(10)

(259496, 29)

,case_enquiry_id,open_dt,target_dt,closed_dt,ontime,case_status,closure_reason,case_title,subject,reason,...,police_district,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,source
0,101002767856,2019-01-01 00:04:32,2019-01-03 08:30:00,2019-01-02 02:22:29,ONTIME,Closed,Case Closed. Closed date : 2019-01-02 02:22:29...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,B3,Dorchester,9,Ward 17,1701,6-8 School St,2124.0,42.2965,-71.0729,Citizens Connect App
1,101002767857,2019-01-01 00:08:52,2019-01-03 08:30:00,2019-01-02 02:22:11,ONTIME,Closed,Case Closed. Closed date : 2019-01-02 02:22:11...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,D14,Allston / Brighton,15,22,2209,INTERSECTION Eastburn St & Mount Vernon St,NaN,42.3594,-71.0587,Citizens Connect App
2,101002767859,2019-01-01 00:50:00,NaN,2019-11-23 11:36:05,ONTIME,Closed,Case Closed. Closed date : 2019-11-23 11:36:05...,Catchbasin,Boston Water & Sewer Commission,Catchbasin,...,E13,Jamaica Plain,11,11,1110,195 South St,2130.0,42.3594,-71.0587,Constituent Call
3,101002767861,2019-01-01 01:26:00,NaN,2019-05-17 12:27:07,ONTIME,Closed,Case Closed. Closed date : 2019-05-17 12:27:07...,Fire,Mayor's 24 Hour Hotline,Notification,...,C11,Dorchester,8,Ward 15,1507,34 Ridgewood St,2122.0,42.3022,-71.0661,Constituent Call
4,101002767862,2019-01-01 01:33:09,2019-01-03 08:30:00,2019-01-02 02:28:35,ONTIME,Closed,Case Closed. Closed date : 2019-01-02 02:28:35...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,B3,Dorchester,9,Ward 17,1701,3 School St,2124.0,42.2968,-71.0727,Citizens Connect App
5,101002767863,2019-01-01 01:56:00,2019-01-03 08:30:00,2019-01-02 02:20:25,ONTIME,Closed,Case Closed. Closed date : 2019-01-02 02:20:25...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,C6,South Boston / South Boston Waterfront,5,Ward 7,0706,22 Ward St,2127.0,42.3298,-71.0546,Citizens Connect App
6,101002767866,2019-01-01 02:39:04,2019-01-03 08:30:00,2019-01-02 02:20:52,ONTIME,Closed,Case Closed. Closed date : 2019-01-02 02:20:52...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,E13,Jamaica Plain,11,Ward 10,1008,81 S Huntington Ave,2130.0,42.3299,-71.1115,Citizens Connect App
7,101002767867,2019-01-01 02:40:09,2019-01-03 08:30:00,2019-01-02 02:18:38,ONTIME,Closed,Case Closed. Closed date : 2019-01-02 02:18:38...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,E13,Jamaica Plain,11,Ward 10,1008,81 S Huntington Ave,2130.0,42.3299,-71.1115,Citizens Connect App
8,101002767868,2019-01-01 02:56:00,2019-01-03 08:30:00,2019-01-01 04:25:10,ONTIME,Closed,Case Closed. Closed date : 2019-01-01 04:25:10...,Requests for Street Cleaning,Public Works Department,Street Cleaning,...,A7,East Boston,1,Ward 1,0111,798 Saratoga St,2128.0,42.3844,-71.0158,Constituent Call
9,101002767869,2019-01-01 03:22:00,NaN,2019-05-17 12:33:03,ONTIME,Closed,Case Closed. Closed date : 2019-05-17 12:33:03...,Police: Full Notifications,Mayor's 24 Hour Hotline,Notification,...,B3,Greater Mattapan,9,Ward 14,1411,19 Johnston Rd,2124.0,42.2875,-71.0913,Constituent Call

# Short Term Rental Eligible

## `str_elgible`

In [23]:
str_eligible_df = pd.read_csv("../data/short-term-rental-eligible/tmptpi1c0rx.csv")

In [24]:
print(str_eligible_df.shape)
str_eligible_df.head(10)

(397952, 17)

,sam_address_id,issued_registration,sam_address,home-share eligible,limited-share eligible,owner-adjacent eligible,owners_current_license_types,income restricted,problem property,problem property owner,open violation count,violations in the last 6 months,legally restricted,unit owner-occupied,building owner-occupied,units in building,building single owner
0,348089,N,15B Ames St,N,N,N,None,Y,N,N,0,0,N,N,N,15,N
1,365307,N,74 Fenway # 35,N,N,N,None,N,N,N,0,0,N,N,N,126,N
2,398117,N,9 Jamaica Pl,N,N,N,None,N,N,N,0,0,N,Y,N,2,N
3,120112,N,44 Rutland Sq,N,N,N,None,N,N,N,0,0,N,N,N,3,N
4,85327,N,1 Lewis Pl,N,N,N,None,Y,N,N,0,0,N,N,N,2,N
5,238985,N,62 G St #2,N,N,N,None,N,N,N,0,0,N,N,N,2,N
6,390500,N,219 I St,N,N,N,None,N,N,N,0,0,N,N,N,2,N
7,341908,N,66 Dana Ave,N,N,N,None,N,N,N,0,0,N,N,N,1,N
8,55,N,69-71 A St,N,N,N,None,N,N,N,5,0,N,N,N,2,N
9,79,N,23 Abbot St,N,N,N,None,N,N,N,6,1,N,N,N,3,N

# Fire Incident Reporting

## `fire_df`

In [25]:
path = r"../data/fire-incident-reporting/"
files = glob.glob(path + "/*.csv")

data_list = []

for file in files:
    df = pd.read_csv(file, index_col=None, header=0)
    data_list.append(df)
    
fire_df = pd.concat(data_list, axis=0, ignore_index=True)

In [26]:
print(fire_df.shape)
fire_df.head(10)

(49555, 24)

,Incident Number,Exposure Number,Alarm Date,Alarm Time,Incident Type,Incident Description,Estimated Property Loss,Estimated Content Loss,District,City Section,...,Street Number,Street Prefix,Street Name,Street Suffix,Street Type,Address 2,XStreet Prefix,XStreet Name,XStreet Suffix,XStreet Type
0,19-0019301,0,04/01/2019,00:38:31,736,CO detector activation due to malfunction ...,0.0,0.0,09,RX,...,800,,PARKER,,ST,,,,,
1,19-0019302,0,04/01/2019,00:52:06,553,Public service ...,0.0,0.0,09,RX,...,39,,ROXBURY,,ST,:3,,,,
2,19-0019303,0,04/01/2019,00:54:27,735,Alarm system sounded due to malfunction ...,0.0,0.0,09,RX,...,131,,WALNUT,,AVE,: #12-2159,,,,
3,19-0019304,0,04/01/2019,00:59:02,714,"Central station, malicious false alarm ...",0.0,0.0,04,BO,...,90,,GAINSBOROUGH,,ST,,,,,
4,19-0019305,0,04/01/2019,01:20:08,700,"False alarm or false call, Other ...",0.0,0.0,04,BO,...,95,,GAINSBOROUGH,,ST,,,,,
5,19-0019306,0,04/01/2019,01:23:31,745,"Alarm system activation, no fire - unintention...",0.0,0.0,06,SB,...,7,,PETERS,,ST,,,,,
6,19-0019307,0,04/01/2019,01:38:52,553,Public service ...,0.0,0.0,07,RX,...,62,,WAVERLY,,ST,,,,,
7,19-0019308,0,04/01/2019,02:03:58,611,Dispatched & cancelled en route ...,0.0,0.0,01,EB,...,127,,MARION,,ST,,,,,
8,19-0019309,0,04/01/2019,02:54:23,621,Wrong location ...,0.0,0.0,06,SB,...,109,,DORCHESTER,,AVE,,,,,
9,19-0019311,0,04/01/2019,03:05:25,553,Public service ...,0.0,0.0,01,EB,...,21,,CHELSEA,,ST,,,,,